FROM python:3.9
WORKDIR /app

COPY flask-api/* ./
RUN pip install -r ./requirements.txt
RUN pip install ./ontology-mapper
ENV FLASK_ENV development

EXPOSE 5000
CMD ["gunicorn", "-b", ":5000", "flask-api:app"]
