# Build Flask API
FROM python:3.9
WORKDIR /app

COPY flask-api/* ./
RUN mkdir /output
## mainly for easy testing; should be able to get rid of when can stop navigating directly to results
COPY flask-api/output/* ./output/
RUN pip install -r ./requirements.txt
ENV FLASK_ENV production

# WORKDIR ./ontology-mapper
RUN pip install .

WORKDIR /app

EXPOSE 5000
CMD ["gunicorn", "-b", ":5000", "-w","2", "flask-api:app"]
